receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: otel
    username: user
    password: password
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  # Add OTLP exporter to Jaeger
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:
    timeout: 200ms
    send_batch_size: 500
    send_batch_max_size: 1000

service:
  telemetry:
    logs:
      level: error

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, otlp]  # Send to both ClickHouse and Jaeger